---
collections:
  - name: onepassword.connect
    source: https://galaxy.ansible.com

# collections:
#   - name: community.general  
#   - name: onepassword.connect

# collections:
# # With just the collection name
# - onepassword.connect

# # With the collection name, version, and source options
# - name: onepassword.connect
#   version: '*'
#   source: 'https://galaxy.ansible.com/onepassword/connect'