---
- name: Install Lamp Stack
  hosts: all
  become: yes

  roles:
  - lamp

  # handlers:
  # - name: Reload Apache
  #   service:
  #     name: apache2
  #     state: reloaded

  # - name: Restart Apache
  #   service:
  #     name: apache2
  #     state: restarted
  
- name: Create 1Password Secret
  hosts: all
  environment:
    OP_CONNECT_HOST: "{{ OP_CONNECT_HOST }}"
    OP_CONNECT_TOKEN: "{{ OP_CONNECT_TOKEN }}"
    OP_VAULT_ID: "{{ OP_VAULT_ID }}"
  tasks:
    - onepassword.connect.generic_item:
        #vault_id: "DevOps"
        #vault_id: "{{ OP_VAULT_ID }}"
        title: Test Item from Ansible
        state: present
        fields:
          - label: Codeword
            value: "hunter2"
            section: "Personal Info"
            field_type: concealed
          - label: Random Code
            generate_value: on_create
            generator_recipe:
                length: 16
                include_letters: yes
                include_digits: yes
                include_symbols: no
      no_log: false
      register: op_item
