---
- name: Install Lamp Stack
  hosts: all
  become: yes

  roles:
  - lamp

  handlers:
  - name: Reload Apache
    service:
      name: apache2
      state: reloaded

  - name: Restart Apache
    service:
      name: apache2
      state: restarted