---
  - name: Installing Packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - apache2
      #- mysql-server
      - php 
      - libapache2-mod-php 
      #- php-mysql
     # - python3-pymysql