---
  - name: Installing LAMP Packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - apache2
      #- mysql-server
      - mariadb-server
      - mariadb-client
      - php 
      - libapache2-mod-php 
      - php-mysql

     # - python3-pymysql